name: main

on:
  push:
    branches:
      - main

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "11.0.15"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build binaries
        run: gradle binary:runtimeZip

      - name: Build docker image
        run: 'scripts/docker.sh'
        shell: bash

      - name: Tag release version
        run: 'scripts/tag.sh'
        shell: bash

      - name: GitHub Release
        run: 'TOKEN=${{ secrets.GITHUBTOKEN }} scripts/github-release.sh'
        shell: bash
