name: release

on:
  push:
    branches:
      - release-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "11.0.15"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.5

      - name: Run tests
        run: gradle test

      - name: Build binaries
        run: gradle binary:runtimeZip

      - name: Update Version
        run: 'BRANCH_NAME=${{ github.ref_name }} scripts/update_version.sh'
        shell: bash
